### ISSUE TITLE
Hey mate, the last case for c4prj3_finish always gets timeout ? How do I get over it?

### ISSUE THREAD

**Issue by afnan47** [AhmedGharib0014/Programming-Fundamentals-c-course-by-Duke-university#3]

**Comment by AlexJones117** [comment]
Hey Afnan47, Hey Ahmed,

Did you figure out how to fix the timeout issue?

**Comment by AlexJones117** [comment]
A few people dropped hints that it had sometime to do with code optimization and shuffle() in particular? Also something about excessive usage of mallocs and reallocs. Please help me if you did figure out how to fix this issue

**Comment by afnan47** [comment]
Actually this code is old, checkout this repo https://github.com/MananOO12/C-Specialization-by-Duke/tree/master/learn2prog
